# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

lado1: float = float(input("Ingrese lado 1: "))
lado2: float = float(input("Ingrese lado 2: "))
lado3: float = float(input("Ingrese lado 3: "))

if lado1 == lado2 and lado2 == lado3:
    perimetro: float = lado1 + lado2 + lado3
    print("Triángulo Equilátero")
    print("Perímetro:", perimetro)

elif lado1 == lado2:
    print("Triángulo Isósceles")
    print("Lados iguales:", lado1, "y", lado2)

elif lado1 == lado3:
    print("Triángulo Isósceles")
    print("Lados iguales:", lado1, "y", lado3)

elif lado2 == lado3:
    print("Triángulo Isósceles")
    print("Lados iguales:", lado2, "y", lado3)

else:
    semiperimetro: float = (lado1 + lado2 + lado3) / 2
    area: float = (semiperimetro *
                    (semiperimetro - lado1) *
                    (semiperimetro - lado2) *
                    (semiperimetro - lado3)) ** 0.5

    print("Triángulo Escaleno")
    print("Área:", area)