# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

edad: int = int(input("Ingrese su edad: "))
ingreso: float = float(input("Ingrese su ingreso mensual: "))

if edad >= 18 and ingreso >= 3000:
    impuesto: float = ingreso * 0.05
    print("Debe tributar.")
    print("Impuesto a pagar: S/", impuesto)
else:
    print("No debe tributar.")