# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

cantidad: int = int(input("Ingrese la cantidad de llantas: "))

if cantidad < 5:
    precio: float = 150
else:
    precio: float = 120

total: float = cantidad * precio

print("Total a pagar: S/", total)