# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

cantidad: int = int(input("Ingrese cantidad de camisas: "))
precioUnitario: float = float(input("Ingrese precio por camisa: "))

subtotal: float = cantidad * precioUnitario

if 1 <= cantidad <= 4:
    porcentajeDescuento: float = 12.5

elif 5 <= cantidad <= 8:
    porcentajeDescuento: float = 20

else:
    porcentajeDescuento: float = 31.5

descuento: float = subtotal * porcentajeDescuento / 100
total: float = subtotal - descuento

print("Compra sin descuento: S/", subtotal)
print("Descuento aplicado: S/", descuento)
print("Compra final: S/", total)