# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

materias: int = int(input("Ingrese cantidad de materias: "))
promedio: float = float(input("Ingrese su promedio: "))

costoCurso: float = 100
total: float = materias * costoCurso

if promedio >= 18:
    mitadCursos: int = materias // 2
    descuento: float = (mitadCursos * costoCurso) * 0.50
else:
    descuento: float = 0

totalPagar: float = total - descuento

print("Monto a pagar: S/", totalPagar)