# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

n1: int = int(input("Ingrese el primer número: "))
n2: int = int(input("Ingrese el segundo número: "))
n3: int = int(input("Ingrese el tercer número: "))

if n1 != n2 and n1 != n3 and n2 != n3:

    opcion: str = input("A = Ascendente, D = Descendente: ")

    lista: list[int] = [n1, n2, n3]

    if opcion.upper() == "A":
        lista.sort()
    else:
        lista.sort(reverse=True)

    print(lista)

else:
    print("Los números deben ser diferentes.")