# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

minutos: int = int(input("Duración de la llamada en minutos: "))
domingo: str = input("¿Es domingo? (S/N): ")
turno: str = input("¿Es turno nocturno? (S/N): ")

costo: float = 0

if minutos <= 5:
    costo = minutos * 1.00

elif minutos <= 8:
    costo = (5 * 1.00) + ((minutos - 5) * 0.80)

elif minutos <= 10:
    costo = (5 * 1.00) + (3 * 0.80) + ((minutos - 8) * 0.70)

else:
    costo = (5 * 1.00) + (3 * 0.80) + (2 * 0.70) + ((minutos - 10) * 0.50)

if domingo.upper() == "S":
    if turno.upper() == "S":
        impuesto: float = costo * 0.05
    else:
        impuesto: float = costo * 0.03
else:
    impuesto: float = 0

total: float = costo + impuesto

print("Costo llamada: S/", costo)
print("Impuesto: S/", impuesto)
print("Total a pagar: S/", total)