# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

hora: int = int(input("Hora: "))
minuto: int = int(input("Minuto: "))
segundo: int = int(input("Segundo: "))
n: int = int(input("Segundos a agregar: "))

segundo += n

minuto += segundo // 60
segundo = segundo % 60

hora += minuto // 60
minuto = minuto % 60

hora = hora % 24

print("Nueva hora:", hora, ":", minuto, ":", segundo)