# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

codigo: int = int(input("Ingrese el código de la zona: "))
minutos: int = int(input("Ingrese la duración de la llamada en minutos: "))

zona: str = ""
costoMinuto: float = 0.0

if codigo == 10:
    zona = "América del Norte"
    costoMinuto = 2.2

elif codigo == 12:
    zona = "América del Centro"
    costoMinuto = 2.5

elif codigo == 20:
    zona = "América del Sur"
    costoMinuto = 1.2

elif codigo == 22:
    zona = "Asia"
    costoMinuto = 3.5

elif codigo == 30:
    zona = "Europa"
    costoMinuto = 3.0

elif codigo == 32:
    zona = "África"
    costoMinuto = 3.2

else:
    print("Código inválido")

if costoMinuto > 0:
    costoTotal: float = minutos * costoMinuto

    print("Zona geográfica:", zona)
    print("Costo por minuto: S/", costoMinuto)
    print("Duración de la llamada:", minutos, "minutos")
    print("Costo total de la llamada: S/", costoTotal)