# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

n1: int = int(input("Ingrese el primer número: "))
n2: int = int(input("Ingrese el segundo número: "))
n3: int = int(input("Ingrese el tercer número: "))

mayor: int = max(n1, n2, n3)
menor: int = min(n1, n2, n3)

print("Número mayor:", mayor)
print("Número menor:", menor)