# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

numeros: list[int] = []
producto: int = 1

for i in range(100, 0, -2):
    numeros.append(i)

for numero in numeros:
    producto *= numero

print("Array:", numeros)
print("Producto:", producto)