# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

ahorroTotal: float = 0

for mes in range(1, 13):

    deposito: float = float(input(f"Ingrese depósito del mes {mes}: "))

    ahorroTotal += deposito

    print("Ahorro acumulado hasta el mes", mes, ":", ahorroTotal)

print("Ahorro total del año:", ahorroTotal)