# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

totalPersonas: int = 0
hombres: int = 0
mujeres: int = 0

sumaEdadHombres: int = 0
sumaEdadMujeres: int = 0

edadMayor: int = 0
edadMenor: int = 0

continuar: str = "S"

while continuar.upper() == "S":

    sexo: str = input("Sexo (H/M): ")
    edad: int = int(input("Edad: "))

    totalPersonas += 1

    if totalPersonas == 1:
        edadMayor = edad
        edadMenor = edad

    if edad > edadMayor:
        edadMayor = edad

    if edad < edadMenor:
        edadMenor = edad

    if sexo.upper() == "H":
        hombres += 1
        sumaEdadHombres += edad
    else:
        mujeres += 1
        sumaEdadMujeres += edad

    continuar = input("¿Desea registrar otra persona? (S/N): ")

promedioHombres: float = 0
promedioMujeres: float = 0

if hombres > 0:
    promedioHombres = sumaEdadHombres / hombres

if mujeres > 0:
    promedioMujeres = sumaEdadMujeres / mujeres

print("Total asistentes:", totalPersonas)
print("Hombres:", hombres)
print("Mujeres:", mujeres)
print("Promedio edad hombres:", promedioHombres)
print("Promedio edad mujeres:", promedioMujeres)
print("Edad mayor:", edadMayor)
print("Edad menor:", edadMenor)