# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

N: int = int(input("Ingrese cantidad de estudiantes (5 a 20): "))

while N < 5 or N > 20:
    N = int(input("Ingrese un valor válido (5 a 20): "))

notas: list[int] = []

for i in range(N):

    nota: int = int(input(f"Ingrese nota del estudiante {i+1}: "))

    while nota < 0 or nota > 20:
        nota = int(input("Nota inválida. Ingrese nuevamente: "))

    notas.append(nota)

mayor: int = max(notas)
menor: int = min(notas)

cantidadMayor: int = notas.count(mayor)
cantidadMenor: int = notas.count(menor)

promedio: float = sum(notas) / N

pares: int = 0
impares: int = 0
aprobados: int = 0
desaprobados: int = 0

for nota in notas:

    if nota % 2 == 0:
        pares += 1
    else:
        impares += 1

    if nota >= 13:
        aprobados += 1
    else:
        desaprobados += 1

porcentajeAprobados: float = aprobados * 100 / N
porcentajeDesaprobados: float = desaprobados * 100 / N

print("Mayor nota:", mayor)
print("Menor nota:", menor)
print("Cantidad con mayor nota:", cantidadMayor)
print("Cantidad con menor nota:", cantidadMenor)
print("Promedio:", promedio)
print("Notas pares:", pares)
print("Notas impares:", impares)
print("Aprobados:", aprobados)
print("Desaprobados:", desaprobados)
print("Porcentaje aprobados:", porcentajeAprobados, "%")
print("Porcentaje desaprobados:", porcentajeDesaprobados, "%")