# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

N: int = int(input("Ingrese el valor de N: "))

sumaPares: int = 0
sumaImpares: int = 0
contPares: int = 0
contImpares: int = 0

for i in range(1, N + 1):

    if i % 2 == 0:
        sumaPares += i
        contPares += 1
    else:
        sumaImpares += i
        contImpares += 1

promedioPares: float = sumaPares / contPares
promedioImpares: float = sumaImpares / contImpares

print("Suma pares:", sumaPares)
print("Promedio pares:", promedioPares)

print("Suma impares:", sumaImpares)
print("Promedio impares:", promedioImpares)