# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

import time

horas: int = 0
minutos: int = 0
segundos: int = 0

while horas < 24:

    print(f"{horas:02d}:{minutos:02d}:{segundos:02d}")

    time.sleep(1)

    segundos += 1

    if segundos == 60:
        segundos = 0
        minutos += 1

    if minutos == 60:
        minutos = 0
        horas += 1