# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

n1: int = int(input("Ingrese el primer número: "))
n2: int = int(input("Ingrese el segundo número: "))

factorial1: int = 1
factorial2: int = 1

cadena1: str = ""
cadena2: str = ""

for i in range(1, n1 + 1):
    factorial1 *= i

    if i == 1:
        cadena1 += str(i)
    else:
        cadena1 += "x" + str(i)

for i in range(1, n2 + 1):
    factorial2 *= i

    if i == 1:
        cadena2 += str(i)
    else:
        cadena2 += "x" + str(i)

comun: int = min(n1, n2)

print(f"{n1}! =", cadena1)
print(f"{n2}! =", cadena2)
print("Son iguales hasta el múltiplo", comun)