# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

N: int = int(input("Cantidad de números: "))
X: int = int(input("Ingrese X: "))

menores: int = 0
mayores: int = 0
iguales: int = 0
entre1yX: int = 0
ninguno: int = 0

for i in range(N):

    numero: int = int(input("Ingrese número: "))

    if numero < X:
        menores += 1

    if numero > X:
        mayores += 1

    if numero == X:
        iguales += 1

    if numero >= 1 and numero <= X:
        entre1yX += 1

    if numero < 1 and numero != X:
        ninguno += 1

print("Menores que X:", menores * 100 / N, "%")
print("Mayores que X:", mayores * 100 / N, "%")
print("Iguales a X:", iguales * 100 / N, "%")
print("Entre 1 y X:", entre1yX * 100 / N, "%")
print("No cumplen ninguna condición:", ninguno * 100 / N, "%")