# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdP3ZXqMUzuqWal-2afiSd5T4IdDLgUK
"""

N: int = int(input("Ingrese la cantidad de números: "))

numero: float = float(input("Ingrese el número 1: "))
mayor: float = numero
menor: float = numero

for i in range(2, N + 1):

    numero = float(input(f"Ingrese el número {i}: "))

    if numero > mayor:
        mayor = numero

    if numero < menor:
        menor = numero

print("Número mayor:", mayor)
print("Número menor:", menor)