# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

nota1: float = float(input("Ingrese la nota 1: "))
nota2: float = float(input("Ingrese la nota 2: "))
nota3: float = float(input("Ingrese la nota 3: "))
nota4: float = float(input("Ingrese la nota 4: "))

promedio: float = (nota1 + nota2 + nota3 + nota4) / 4

print("El promedio es:", promedio)