# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

montoBase: float = float(input("Ingrese el monto de la compra: "))
porcentajeDescuento: float = float(input("Ingrese el porcentaje de descuento: "))
pagoCliente: float = float(input("Ingrese el dinero entregado por el cliente: "))

descuento: float = montoBase * porcentajeDescuento / 100

totalPagar: float = montoBase - descuento

cambio: float = pagoCliente - totalPagar

print("Descuento aplicado: S/", descuento)
print("Total a pagar: S/", totalPagar)
print("Cambio a entregar: S/", cambio)