# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

Vi = 0
a = 0.8
t = 30

Vf = Vi + (a * t)

print("La velocidad final es:", Vf, "m/s")