# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

monto: int = int(input("Ingrese el monto a retirar: "))

billetes200: int = monto // 200
monto = monto % 200

billetes100: int = monto // 100
monto = monto % 100

billetes50: int = monto // 50
monto = monto % 50

billetes20: int = monto // 20
monto = monto % 20

billetes10: int = monto // 10
monto = monto % 10

monedas5: int = monto // 5
monto = monto % 5

monedas1: int = monto

print("Billetes de 200:", billetes200)
print("Billetes de 100:", billetes100)
print("Billetes de 50:", billetes50)
print("Billetes de 20:", billetes20)
print("Billetes de 10:", billetes10)
print("Monedas de 5:", monedas5)
print("Monedas de 1:", monedas1)