# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

capital: float = float(input("Ingrese el capital a invertir: "))

tasaMensual: float = 0.02
meses: int = 12

ganancia: float = capital * tasaMensual * meses

montoFinal: float = capital + ganancia

print("Ganancia después de un año:", ganancia)
print("Monto final después de un año:", montoFinal)