# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

A: float = float(input("Ingrese el lado A: "))
B: float = float(input("Ingrese el lado B: "))
C: float = float(input("Ingrese el lado C: "))

areaRectangulo: float = B * C

areaTriangulo: float = (B * (A - C)) / 2

areaTotal: float = areaRectangulo + areaTriangulo

print("Área del terreno:", areaTotal, "m²")