# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

horas: int = int(input("Ingrese las horas utilizadas: "))
minutos: int = int(input("Ingrese los minutos adicionales: "))

costoHoras: float = horas * 5.00
costoMinutos: float = minutos * 0.10

totalPagar: float = costoHoras + costoMinutos

print("Monto a pagar: S/", totalPagar)