# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

edad: int = int(input("Ingrese su edad en años: "))

meses: int = edad * 12
semanas: int = edad * 52
dias: int = edad * 365
horas: int = dias * 24

print("Meses vividos:", meses)
print("Semanas vividas:", semanas)
print("Días vividos:", dias)
print("Horas vividas:", horas)