# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

inversion1: float = float(input("Ingrese la inversión de la persona 1: "))
inversion2: float = float(input("Ingrese la inversión de la persona 2: "))
inversion3: float = float(input("Ingrese la inversión de la persona 3: "))

total: float = inversion1 + inversion2 + inversion3

porcentaje1: float = (inversion1 / total) * 100
porcentaje2: float = (inversion2 / total) * 100
porcentaje3: float = (inversion3 / total) * 100

print("Porcentaje de la persona 1:", porcentaje1, "%")
print("Porcentaje de la persona 2:", porcentaje2, "%")
print("Porcentaje de la persona 3:", porcentaje3, "%")