# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo0LIrAJ6gfA-OmU9xkoYIiSG-9tn6pE
"""

sueldoBase: float = float(input("Ingrese el sueldo base: "))

venta1: float = float(input("Ingrese el valor de la venta 1: "))
venta2: float = float(input("Ingrese el valor de la venta 2: "))
venta3: float = float(input("Ingrese el valor de la venta 3: "))

totalVentas: float = venta1 + venta2 + venta3

comision: float = totalVentas * 0.25

sueldoTotal: float = sueldoBase + comision

print("Comisión obtenida:", comision)
print("Sueldo total del mes:", sueldoTotal)